### ISSUE TITLE
Lose Ability to Type After Going Full-Screen with Safari 8.0.2

### ISSUE THREAD

**Issue by jelyman2** [tholman/zenpen#106]
Just found zenpen and love it, but when I go full-screen (using the icon on the left) with Safari 8.0.2 and OS X 10.10, I lose the ability to type anything but symbols. Letters and numbers don't appear (as if my cursor is in a space that doesn't allow input at all.) This issue is not reproducible with Chrome or Firefox.

**Comment by tholman** [comment]
Urgh, this is a Safari bug (or feature, as they see it) ... to stop people from making a browser fullscreen, and then mimicking native features (url bar, for example) to get people confused, and eventually scrape their data.

The best fix, would be to hide it on safari, but alas, this feature isn't something easily detectable either, and browser sniffling generally isn't great :(

**Comment by jelyman2** [comment]
Interesting. Good to know. FWIW, I can use the spacebar in full screen mode!


Johnathan Lyman*, *MCP
Tel: (425) 471-8603
jelyman@gmail.com
Twitter <http://twitter.com/theejl> | LinkedIn
<http://linkedin.com/in/johnathanlyman> | http://jlyman.net

**Comment by tholman** [comment]
Safari/Webkit Have definitely done a poor job on that implementation. They should almost not let it go to full mode, when you pass the parameter to request being able to use the keyboard at the same time.

:(

**Comment by jelyman2** [comment]
I know this is a bit old but I wanted to update and say that I can't replicate this issue, anymore. Perhaps whatever support form WebKit that was lacking is now at least present enough to make ZenPen work? :) Running Safari 8.0.7 on 10.10.4.
