### ISSUE TITLE
How to add custom styles? 

### ISSUE THREAD

**Issue by Kondra007** [tholman/zenpen#109]
Hello. Could you please briefly explain how to add custom styles to ZenPen?
F.ex I want an  `<s></s>` tag. Where shall I add it?

**Comment by tholman** [comment]
Well, if you're creating your own version, you'd add the strikethrough to the css, and then include it also in the editor/ui js (copy how bold, and italic has been done)

There are no plans though, to add this to the editor as it stands though.

**Comment by Kondra007** [comment]
Thanks for the answer.
However, I'm looking through [Style.css](https://github.com/tholman/zenpen/blob/master/css/style.css) file and can't find anything about current bold, italic and blockquote..

**Comment by tholman** [comment]
Ahh, this is because they're natively bold/italic in the browser. I imagine `s` would be similar?

If not, you can add it into your version?

**Comment by Kondra007** [comment]
I'll try. But I don't know where to but this code :( 
```
if ( hasNode( currentNodeList, 'I') ) {
			italicButton.className = "italic active"
		} else {
			italicButton.className = "italic"
		}
```
I think this code must be connected to CSS, right? (I'm quite noobish here, sorry)

**Comment by tholman** [comment]
Well, thats the classname for the button in the ui... not in the styles for the page. The currentNodeList containing an `I` means that its found an `<i>` tag in the selected area. That would map to the css (but doesn't appear there, because the browser natively adds italic to `<i>` tags.

**Comment by Kondra007** [comment]
And where this `<i>` tag is appended to selected text? I really don't see it anywhere.

**Comment by tholman** [comment]
Ahh, its done using the rich text editing api... here:

https://github.com/tholman/zenpen/blob/master/js/editor.js#L242-L244

You can read more about it here too, I believe it does support "strikethrough"

https://developer.mozilla.org/en-US/docs/Web/API/document.execCommand

:)

**Comment by Kondra007** [comment]
Well, sorry, I have no idea what to do. All my attemps end as fail, I don't see how to add element to options box, I did **exactly** the same you did with other buttons with newly created one: 
1. added `strokeButton`;

2. added
```
strokeButton = textOptions.querySelector( '.italic' );
		strokeButton.onclick = onStrokeClick;
```
(italic, because `'.stroke'` returns an error "Can't set property of onclick as null")

3. edited `updateBubbleStates()`
```
if ( hasNode( currentNodeList, 'S') ) {
			strokeButton.className = "stroke active"
		} else {
			strokeButton.className = "stroke"
		}
```
4. added new funtion (thanks for Mozilla link, btw, it helped to choose the correct command):
```
function onStrokeClick() {
		document.execCommand( 'strikeThrough', false);
	}
```

and nothing! No buttons appear in editor. Maybe someone more clever manage to add new functions, not me.

**Comment by tholman** [comment]
Ahh, you were getting closer! But ok :)
