### ISSUE TITLE
UI Discoverability: Erasing title

### ISSUE THREAD

**Issue by vanceza** [tholman/zenpen#113]
I'm not exactly sure how to solve this, but I didn't realize for a long time that you could erase the title--when I highlighted the main paragraph the title can't be highlighted at the same time, and so I assumed it wasn't editable.

Since it's a visual distraction, this almost put me off using Zen Pen.

**Comment by tholman** [comment]
Good call. Perhaps I'll add something in the main description about the title :)

**Comment by dboudro** [comment]
In Chrome the cursor begins blinking at the title... maybe there is a way to ensure this happens in all browsers?

**Comment by tholman** [comment]
That would do it!

Wonder why thats not working at the moment...
