### ISSUE TITLE
Mimic typewriter effect by keeping text in the middle

### ISSUE THREAD

**Issue by felippenardi** [tholman/zenpen#116]
This is a suggestion to add a Typewriter icon on the left corner that enables a special mode that will keep the last words always on the middle.

When the words start reaching the middle of the screen, every new line pushes the text up so the last line always stay on the middle.

**Comment by tholman** [comment]
Appreciate the comment, but want to keep zenpen simple and uncluttered. I'm a bit concerned about adding new things, and confusing it a little more.
