### ISSUE TITLE
Paste image from clipboard

### ISSUE THREAD

**Issue by dandv** [tholman/zenpen#119]
Is this within the scope of the project? I'm [comparing WYSIWYG editors](https://github.com/iDoRecall/media/blob/master/Comparison-of-JavaScript-WYSIWYG-editors.md) and looking for this feature.

BTW, really like the auto-convert to markdown!

**Comment by tholman** [comment]
Hey mate, 

Nah, copying images isn't going to be part of the scope. ZenPen is more of a "sit down and get the words out" application, rather than a fully fledged "write here, and we will publish it" kind of thing :) :dancer: Sorry!

**Comment by dandv** [comment]
Oh, no problem. I find that most blogs or content, indeed, nowadays, does use an image per post and the more convenience in getting that image there, the better. I guess I'll go with [Trumbowyg](alex-d.github.io/Trumbowyg/) for now. Thanks!

**Comment by tholman** [comment]
Bo worries :D

On Mon, Jun 1, 2015 at 8:09 PM, Dan Dascalescu <notifications@github.com>
wrote:

> Oh, no problem. I find that most blogs or content, indeed, nowadays, does
> use an image per post and the more convenience in getting that image there,
> the better. I guess I'll go with Trumbowyg
> <http://alex-d.github.io/Trumbowyg/> for now. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/tholman/zenpen/issues/119#issuecomment-107750639>.
>



-- 
Tim Holman
tholman.com
