### ISSUE TITLE
not an issue

### ISSUE THREAD

**Issue by akjunior** [tholman/zenpen#131]
Really long words don't break?

try....
p{
	overflow-wrap: break-word;
	word-wrap: break-word;
	-webkit-hyphens: auto;
	-ms-hyphens: auto;
	-moz-hyphens: auto;
	hyphens: auto;
}

**Comment by BDMorrell** [comment]
Wouldn't this fit into a pull request?

**Comment by TJScalzo** [comment]
I believe this was solved in 491e944. Am I correct?

**Comment by tholman** [comment]
Yep!
