### ISSUE TITLE
Another title and section

### ISSUE THREAD

**Issue by Extellion** [tholman/zenpen#132]
So I come up with and Idea but I guess someone has already thought about this. 

The idea is quite simple, adding a button which will append a h1 after the section, every h1 created will have a section related (as if it was the first one). So you can add something like a chapter.

What do you think of that ?

**Comment by tholman** [comment]
Hey!

Ahh, we have had the request before. Ultimately, deciding to leave it out. Aim really to be good for short bursts of writing, but without getting too complex with more and more stuff! 💃
