### ISSUE TITLE
Add Insert Image Option

### ISSUE THREAD

**Issue by penguoir** [tholman/zenpen#136]
Have an option to insert an image from your computer or from the internet into ZenPen. Perhaps something similar to markdown.

**Comment by Boikolek** [comment]
it will be nice to place an imagefile from the clipboard

**Comment by vixalien** [comment]
For this, you can always try: <editorjs.org>, which os full-featured, while zenpen is both minimalistic and zen!!

**Comment by aditya95sriram** [comment]
Probably check out #85 where the code owner mentions that he wants to keep ZenPen as a text-only minimal editor.

**Comment by penguoir** [comment]
Ah thanks, @aditya95sriram, this is a duplicate of #85.
