### ISSUE TITLE
Move Word Count Indicator

### ISSUE THREAD

**Issue by GeraldNDA** [tholman/zenpen#137]
The location of the word count indicator not only looks bad, but it is definitely not where I would expect it. Usually in the case of reading indicators it's on the top area. Or potentially move it to the left side where there is usually no scroll bar, or on the inside of the viewport or even on the bottom of the screen. It really isn't that noticeable where it is, and I think moving it to the top like the standard or the bottom of the viewport would be the best spot for it.

**Comment by tholman** [comment]
This is where its been for years without any problem or complaint, and its where it will stay.
