### ISSUE TITLE
Lists?

### ISSUE THREAD

**Issue by stepmr** [tholman/zenpen#46]
Support for lists would be awesome... may have time to try something out next week...

Medium's editor does a pretty good job with this..

> You can make bulleted or numbered lists. To start a list, type a dash or 1. and then start typing your first item. Once you hit “return” it will change to a list.
- https://medium.com/help-center/128f049a7ad

**Comment by tholman** [comment]
Nah, no real intention to add this... you can do fake lists when writing. /w dashes, or bullet text. Thats good enough for me.
